### ISSUE TITLE
reactstrap-validation-date: Failed prop type: withStyles(DateRangePicker)

### ISSUE THREAD

**Issue by diegodesouza** [Availity/availity-react#540] opened 2020-05-06 15:24 UTC
### Current Behavior

```
Warning: Failed prop type: withStyles(DateRangePicker): unknown props found: start, end, type
    in withStyles(DateRangePicker) (at AvDateRange.js:606)
    in AvDateRange (at Filter.js:67)
```

Filter.js
```
import {AvForm} from 'availity-reactstrap-validation';
import {AvDateRange} from '@availity/reactstrap-validation-date';
import '@availity/reactstrap-validation-date/styles.scss';

 <AvForm>
              <AvDateRange
                name="standAlone"
                start={{
                  name: 'date.start',
                  value: '01/02/2001',
                }}
                end={{
                  name: 'date.end',
                  value: '01/04/2001',
                }}
              />
</AvForm>
```

**Comment by GoPro16** [comment] 2020-05-06 15:35
Duplicate of https://github.com/airbnb/react-dates/issues/950

This is just a hot loader issue and is only a warning in dev mode.

However we did recently add a different hot loader to workflow if you change you `workflow.js` file to use the new loader it may remove the warning. If it does not you can safely ignore for now until a patch is submitted to fix it in the `react-hot-loader` repo.

```js
config.development.hotLoader = {
   enabled: true,
   experimental: true
}
```

**Closed as completed by GoPro16** 2020-05-06 15:35 UTC
