### ISSUE TITLE
AvRegionSelect - Searching for 'California' then tabbing won't select California

### ISSUE THREAD

**Issue by diegodesouza** [Availity/availity-react#662] opened 2020-12-18 20:40 UTC
## ❓Question

I'm using the AvRegionSelect, and noticed that if I type 'California' then `Tab` to go to the next field. It is not selecting the value `California` like `AvOrganizationSelect` does.

```
                <AvOrganizationSelect
                  id="organizations"
                  name="organizations"
                  placeholder="Select an Organization"
                  label="Enter Organization Name"
                  labelHidden
                  onChange={this.onSelectedOrganization}
                  value={selectedOrganization}
                  required
                  validate={{
                    required: {
                      value: true,
                      errorMessage: "Please select an Organization."
                    }
                  }}
                />
```

```
<AvRegionSelect
                name="state"
                label="State"
                labelHidden
                onChange={obj => this.onStateChangeHandler(obj)}
                required
                placeholder="Select a state"
                validate={{
                  required: {
                    value: true,
                    errorMessage: "Please select a State."
                  }
                }}
              />
```

**Comment by diegodesouza** [comment] 2020-12-18 20:42
@nylon22 Do you have any knowledge of this?

**Comment by nylon22** [comment] 2020-12-21 18:35
This behavior is fixed in the `@availity/select`, but not in `@availity/reactstrap-validation-select`. There are no plans at this time to maintain feature parity between the two.

**Comment by nylon22** [comment] 2020-12-21 20:59
related #533

**Comment by diegodesouza** [comment] 2020-12-22 01:46
My guess is that `@availity/select` would only work with `@availity/form` also correct? and not the form from `'availity-reactstrap-validation'`

**Comment by nylon22** [comment] 2020-12-22 14:30
that is correct

**Comment by diegodesouza** [comment] 2021-01-05 18:57
Ok thank you @nylon22

**Comment by diegodesouza** [comment] 2021-01-05 21:42
@nylon22 I'm afraid to say the `@availity/form` way also doesn't search or tabs. Went through the process of migration from the`availity-reactstrap-validation` to `@availity/select` to see if that would solve this problem.

**Comment by diegodesouza** [comment] 2021-01-05 21:48
https://user-images.githubusercontent.com/7575914/103703531-b288a680-4f75-11eb-910e-3b353204cd9e.mov

Here i had the `defaultToCurrentRegion`. will be removing it.

**Comment by diegodesouza** [comment] 2021-01-05 21:59
Noticed this in my console when tabbing out of it 
`Warning: Invalid field name. Either pass `useField` a string or an object containing a `name` key.`

```
              <AvRegionSelect
                label="State"
                id="state"
                name="state"
                onChange={this.onStateChangeHandler}
                placeholder="Select a state"
                value={state}
              />
```

**Closed as completed** 2021-01-06 20:40 UTC

**Comment by nylon22** [comment] 2021-01-07 15:03
@diegodesouza Please reopen this issue if the problem is not resolved after you update to the `latest` version of `@availity/select`

**Comment by diegodesouza** [comment] 2021-01-11 19:33
@nylon22 please check this [example](https://stackblitz.com/edit/react-ffq5ez?)  on the `Select` and options I'm passing to it. We have an example where we need to do a multi select search. The options are populated correctly, the issue is when i do the multi select. I'm able to select one and then everything disappears except one other value.
