### ISSUE TITLE
Jest throws Unexpected identifier AvSelect

### ISSUE THREAD

**Issue by napsta32** [Availity/availity-react#185] opened 2019-06-28 06:28 UTC
I am trying to start a simple test with jest using babel transpilation and unexpected identifier is thrown. It looks like reactstrap and loadash don't have the same issues. My current babel configuration is:

```
module.exports = {
    presets: [
        ["@babel/preset-react"],
        ["@babel/preset-env"],
        ["@babel/preset-flow"],
    ],
    plugins: ["@babel/plugin-proposal-class-properties"],
};
```
And the jest error:
``` 
 FAIL  tests/smoke/Login.test.js
  ● Test suite failed to run

    /mnt/d/.../front_end/main/node_modules/@availity/reactstrap-validation-select/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import AvSelect from './AvSelect';
                                                                                                    ^^^^^^^^

    SyntaxError: Unexpected identifier

      4 | import { Label } from 'reactstrap';
      5 | import _debounce from 'lodash.debounce';
    > 6 | import AvSelect, { AvSelectField } from '@availity/reactstrap-validation-select';
        | ^
     [...]

      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:471:17)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:513:25)
      at Object.<anonymous> (src/views/...:6:1)
```

Tests are unable to start with jest + enzyme.

**Comment by nylon22** [comment] 2019-06-28 13:08
Appears to be dupe of #22

**Comment by GoPro16** [comment] 2019-08-19 20:40
Closing this issue, if you are having issues/concerns please comment on #22

**Closed as completed by GoPro16** 2019-08-19 20:40 UTC
Labels: duplicate
