### ISSUE TITLE
PageHeader | render breadcrumb Url from space link

### ISSUE THREAD

**Issue by GoPro16** [Availity/availity-react#324] opened 2019-10-07 16:19 UTC
### Current Behavior
Currently, we take the `spaceId` and `spaceName` from the props/spaceFromSpaceId and use that to render the breadcrumb before the `appName`.

https://github.com/Availity/availity-react/blob/master/packages/page-header/PageHeader.js#L68

However, we have the link hardcoded to always navigate back to `web/spaces/spaces/{spaceId}`. In just about all cases, if the spaceId is of type `payer space` we the `link.url` property of the space is that url. When we want to navigate back to the previous page it will always trying going to a `web/spaces/spaces` with the that spaceId.

### Desired Behavior
Given that we find a space from the `spaceFromSpaceId` we should use the `link.url` from that space rather than the hard coded url.

### Suggested Solution
Add logic to check if the `spaceFromSpaceId` is found and if so use the `link.url` from that, otherwise we can default to `spaces/spaces`. 

### Who does this impact? Who is this for?
Developers who are building sub applications not off payer spaces.

**Comment by nylon22** [comment] 2019-10-07 16:29
I think this may be a duplicate of #17 . I don't think this functionality was ever implemented. We handle it slightly differently in `availity-angular`: https://github.com/Availity/availity-angular/commit/3860dc7d53dedad3db6cb397325eb3f8b633967c

I think we may want to go `useSpaceUrl` to avoid unexpected behavior. Thoughts?

**Comment by GoPro16** [comment] 2019-10-07 16:42
All `Payer Space` type `Spaces` already have the URL the same as what it is for the hard coded one. We can still do the default behavior if its not wrapped in the `Spaces` Provider but in the end if we want `Spaces` to be a true CMS with `PageHeader` as a CMS-like component then the Space url should always be the default. 

Unless you can think of an edge case where you would want to display a different space name but redirect to a different url then yes we can add that prop.

**Comment by nylon22** [comment] 2019-10-07 17:11
That sounds good to me. I do know of times where we want to display a different space name, but we already have `spaceName` prop for that.

I think just make sure we keep `/web/spaces/spaces/#/${spaceId}` as default and we should be good

**Closed as completed** 2019-10-08 15:35 UTC
