### ISSUE TITLE
Module parse failed (Failed to compile)

### ISSUE THREAD

**Issue by fetahokey** [Availity/availity-react#444] opened 2020-02-08 07:38 UTC
## ❓failed to compile my react project after installing @availity/upload !

Message error: 
**You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file**
webpack.json: 

> `  ],
>     module: {
>         rules: [
>             {
>                 test: /\.js$/,
>                 exclude: /node_modules/,
>                 use: 'babel-loader'
>             },`

**Comment by GoPro16** [comment] 2020-02-10 14:09
Duplicate of #22

**Closed as completed by GoPro16** 2020-02-10 14:09 UTC
